<?php
/**
 * encoding: utf-8
 * 
 * this file is auto generated by db-schema-dump (or others) command.
 */

class Db_Schema_Base extends ActiveGateway_Schema
{
    public function define($version = 20130122222452)
    {

        $this->setVersion($version);

        $this->createTable('foo')
            ->column('fooo')->type('list', array('1','2'))->defaultValue('1')
            ->engine('MyISAM')->charset('utf8')->collate('utf8_unicode_ci');

        $this->createIndex('foo', 'fooo')->setName('index_foo_on_fooo');

        $this->createTable('hoge')
            ->column('identifier')->type('string', 255)
            ->column('updated_at')->type('integer', 11)
            ->column('deleted_at')->type('integer', 11)
            ->engine('MyISAM')->charset('utf8')->collate('utf8_unicode_ci');

        $this->createUnique('hoge', 'identifier')->setName('unique_hoge_on_identifier');

        $this->createTable('uhouho')
            ->column('list')->type('list', array('1'))->defaultValue('1')
            ->column('created_at')->type('integer', 11)
            ->column('updated_at')->type('integer', 11)
            ->column('deleted_at')->type('integer', 11)
            ->column('active')->type('list', array('0','1'))->defaultValue('1')
            ->engine('InnoDB')->charset('utf8')->collate('utf8_unicode_ci');

    }
}