language: php

php:
    - 5.4

env:
    - ONIKIRI_SPEC_MYSQL_USER="root" ONIKIRI_SPEC_MYSQL_DATABASE="app"

notifications:
    email:
        - 8823-scholar@hayabusa-lab.jp

branches:
    only:
        - works/spec
        - feature/3.0

before_script:
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE app'

script:
    - Samurai/Console/app spec

