language: php

php:
    - 5.4

env:
    global:
        - secure: "luTz9xgNoZ6XyJIpBBFqq6DBM/kvn315FEyRVmU6L3nyaNChbNF1sFYfV8MIpGHYZESBoomy0URcVGyBkURGzjg1Hk016RcztYO9LS01Isi9u2ZqjuchzBFA9Qo/I7F5kblqYB7l0qV5nxMkx9CUbHBUbMcJ4SSBs6aftjp/bFM="
        - ONIKIRI_SPEC_MYSQL_USER="root" ONIKIRI_SPEC_MYSQL_DATABASE="app"
        - ONIKIRI_SPEC_PGSQL_USER="postgres" ONIKIRI_SPEC_PGSQL_DATABASE="app"

notifications:
    email:
        - 8823-scholar@hayabusa-lab.jp

branches:
    only:
        - works/spec
        - feature/3.0

before_script:
    - phpenv config-add .travis/php.ini
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE app'
    - psql -c 'CREATE DATABASE app;' -U postgres

script:
    - Samurai/Console/app spec

after_script:
    - vendor/bin/coveralls -v

