#
# SamuraiFW用の設定ファイル
#

## container
container:
    name : samurai
    class : Samurai_Container
    dicon : config/samurai/samurai.dicon
    
## action
action:
    prefix      : action
    default     : index
    request_key : action
    config_file : samurai.yml
    dicon_file  : samurai.dicon
    
## filter
filter:
    prefix : filter
    routing:
        enable : true
    
## directory
directory:
    samurai : %SAMURAI_DIR%
    ## 以下のディレクトリはdirectory.samuraiをルートとした相対パスで指定すること
    ## 「/」から始めることによって絶対パスによる指定も可能
    bin       : bin
    component : component
    action    : component/action
    core      : component/samurai
    filter    : component/filter
    config    : config
    library   : library
    template  : template
    log       : log
    locale    : locale
    skeleton  : skeleton
    temp      : temp
    resource  : resource
    spec      : spec
    
## 文字コード
encoding:
    input    : UTF-8
    output   : UTF-8
    config   : UTF-8
    script   : UTF-8
    template : UTF-8
    skeleton : UTF-8
    internal : UTF-8
    
## ログ
loggers:
    
## エラー
error:
    validate : invalidInput
    token    : invalidToken
    upload   : invalidUpload
    auth     : invalidAuth
    login    : login
    debug    : debug
    device   : invalidDevice
    
## 機能の調節
enable:
    samuraiinfo : true
    request_injection : false
    yaml_cache : true
    
## その他色々
etc:
    is_https_function : null
