#
# SamuraiFW用の設定ファイル
#

## actionディレクティブ
action:
    default : utility_locate
    
## generatorディレクティブ
generator:
    generator:
        package   : 'Package'
        author    : 'Foo Bar <foo@bar.jp>'
        copyright : 'Foo Project'
        license   : ''
    encoding:
        config   : UTF-8
        script   : UTF-8
        template : UTF-8
        skeleton : UTF-8
        output   : UTF-8
    directory:
        component : 'component'
        action    : 'component/action'
        template  : 'template'
        spec      : 'spec'
        migration : 'db/migrate'
        skeleton  : 'skeleton'
        www       : 'public_html'
    action:
        config_file : samurai.yml
        dicon_file  : samurai.dicon
    
## その他
enable:
    request_injection : true
    yaml_cache : false

