###
 # generator/config/samurai/config.generator.yml
 # 
 # SamuraiFW用の設定ファイル。
 # generator用。
 # 
 # @package    Samurai
 # @subpackage Config.Samurai
 # @copyright  Befool, Inc
 # @author     Satoshi Kiuchi <satoshi.kiuchi@befool.co.jp>
 # @license    http://opensource.org/licenses/bsd-license.php  The modified BSD License
 #/
 
## actionディレクティブ
action:
    default : utility_locate
    
## generatorディレクティブ
generator:
    generator:
        package   : 'Package'
        author    : 'Foo Bar <foo@bar.jp>'
        copyright : 'Foo Project'
        licence   : 'http://www.php.net/license/3_01.txt The PHP License, version 3.01'
    encoding:
        config   : UTF-8
        script   : UTF-8
        template : UTF-8
        skeleton : UTF-8
        output   : UTF-8
    directory:
        component : 'component'
        action    : 'component/action'
        template  : 'template'
        skeleton  : 'skeleton'
        www       : 'public_html'
    action:
        config_file : samurai.yml
        dicon_file  : samurai.dicon
    
## その他
enable:
    request_injection : true
    yaml_cache : false
